import 'dart:ffi';
import 'dart:typed_data';
import 'package:ffi/ffi.dart';
import 'package:test/test.dart';
import 'package:assimp/assimp.dart';
import '../lib/src/bindings.dart';
import 'test_utils.dart';

// DO NOT EDIT (generated by tool/testgen)

void main() {
  prepareTest();

  test('null', () {
    expect(Camera.fromNative(null), isNull);
  });

  test('size', () {
    expect(sizeOf<aiCamera>(), equals(1080));
  });

  test('3mf', () {
    testCameras('3mf/box.3mf', (cameras) {
      expect(cameras.length, isZero);
    });
    testCameras('3mf/spider.3mf', (cameras) {
      expect(cameras.length, isZero);
    });
  });

  test('fbx', () {
    testCameras('fbx/huesitos.fbx', (cameras) {
      expect(cameras.length, equals(1));
      expect(cameras.elementAt(0).name, equals('Camera'));
      expect(cameras.elementAt(0).position, vector3MoreOrLessEquals(Vector3(0, 0, 0)));
      expect(cameras.elementAt(0).up, vector3MoreOrLessEquals(Vector3(0, 1, 0)));
      expect(cameras.elementAt(0).lookAt, vector3MoreOrLessEquals(Vector3(1, 0, 0)));
      expect(cameras.elementAt(0).horizontalFov, moreOrLessEquals(0.857556));
      expect(cameras.elementAt(0).clipPlaneNear, moreOrLessEquals(10));
      expect(cameras.elementAt(0).clipPlaneFar, moreOrLessEquals(10000));
      expect(cameras.elementAt(0).aspect, moreOrLessEquals(1.33333));
    });
  });

  test('obj', () {
    testCameras('Obj/Spider/spider.obj', (cameras) {
      expect(cameras.length, isZero);
    });
  });

}
