import 'dart:ffi';
import 'dart:typed_data';
import 'package:ffi/ffi.dart';
import 'package:test/test.dart';
import 'package:assimp/assimp.dart';
import 'package:assimp/src/bindings.dart';
import 'test_utils.dart';

// DO NOT EDIT (generated by tool/testgen)

void main() {
  prepareTest();

  test('null', () {
    expect(AssimpMatrix3.fromNative(null), isNull);
  });

  test('size', () {
    expect(sizeOf<aiMatrix3x3>(), equals(36));
  });

}
