import 'dart:ffi';
import 'dart:typed_data';
import 'package:ffi/ffi.dart';
import 'package:test/test.dart';
import '../lib/assimp.dart';
import '../lib/src/bindings.dart';
import 'test_utils.dart';

// DO NOT EDIT (generated by tool/testgen)

void main() {
  prepareTest();

  test('null', () {
    expect(NodeAnim.fromNative(null), isNull);
  });

  test('size', () {
    expect(sizeOf<aiNodeAnim>(), equals(1080));
  });

}
