name: Build

# for vcpkg
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    continue-on-error: true
    steps:
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: dev
    - name: Install Assimp on Ubuntu
      if: matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04'
      run: sudo apt update && sudo apt install -y libassimp-dev
    - name: Install Assimp on macOS
      if: matrix.os == 'macos-latest'
      run: brew install assimp
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup MSVC
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install vcpkg
      if: matrix.os == 'windows-latest'
      uses: lukka/run-vcpkg@v3
      with:
        setupOnly: true
        vcpkgDirectory: '${{github.workspace}}/vcpkg'
        vcpkgGitCommitId: '12ab060a3d43b56c6689ac7fe5861c6f9138c568'
    - name: Install Assimp on Windows
      if: matrix.os == 'windows-latest'
      run: vcpkg install assimp:x64-windows
      working-directory: '${{github.workspace}}/vcpkg'
    - name: Get dependencies
      run: dart pub get
    - name: Set environment on macOS
      if: matrix.os == 'macos-latest'
      uses: allenevans/set-env@v2.0.0
      with:
        DYLD_LIBRARY_PATH: '/usr/local/opt/assimp/lib'
        ASSIMP_LIBRARY_PATH: '/usr/local/opt/assimp/lib/libassimp.5.dylib'
    - name: Set environment on Windows
      if: matrix.os == 'windows-latest'
      uses: allenevans/set-env@v2.0.0
      with:
        ASSIMP_LIBRARY_PATH: '${{github.workspace}}\vcpkg\installed\x64-windows\bin\assimp-vc142-mt.dll'
    - name: Run tests
      run: dart test
    - name: Measure coverage
      if: matrix.os == 'ubuntu-20.04'
      run: dart run test_cov
    - name: Upload coverage
      if: matrix.os == 'ubuntu-20.04'
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage/lcov.info
